### ISSUE TITLE
Response body is duplicated when piping

### ISSUE THREAD

**Issue by modulitos** [tommymessbauer/hammock#15] opened 2015-06-30 10:20 UTC
For example, when my http request returns the following:

```
var response = require('response')
...
myHandlerToTest.prototype.myMethod = function (req, res) {
  ...
  return response().txt('hi').pipe(res)
}
```

and my response is as follows:

```
  var response = hammock.Response()
  myHandlerToTest.myMethod(request, response)
  response.on('end', function (err, data) {
    console.log("data.body:", data.body) // This is 'hihi' ?!?!
    ...
  }
```

then `data.body` is `hihi`. I discovered that the body is duplicated only when something is piped into the response. Looking at the response code, this is because `response.write(str)` and `this.on('pipe', function (src) {...})` are both pushing chunks onto `response.buffer`, causing the body to be duplicated.

I believe this concern was raised in [this comment](https://github.com/tommymessbauer/hammock/commit/45cc549027be86fc615fa6ffa8d41c9f1ec2df47), but was never addressed, or the problem somehow resurfaced. 

I am using Node v0.12.5.

**Comment by BinChang** [comment] 2016-01-17 05:47
Just out of curiosity,  I tried to reproduce this bug, but could not get it,  here is the  [test file](https://github.com/BinChang/hammock/blob/reproduce_pipe_bug/tests/pipe.js)

**Comment by tommymessbauer** [comment] 2017-11-15 02:09
Looks like this is not reproducible in current LTS releases so I'm going to close it. Sorry for being slow to respond here.

**Closed by tommymessbauer** 2017-11-15 02:09 UTC
